### ISSUE TITLE
Plotting function for Figure 2A and 2D

### ISSUE THREAD

**Issue by ttszen** [OscarGVelasco/LotOfCells#1]
Hi! Thank you very much for the very interesting and useful tool. I'm trying to implement the figures from panel 2A and 2D. I was wondering if you could please point me to the direction of the plotting function for these panels? 

It'd be great to get your thoughts and happy to discuss further.

**Comment by ttszen** [comment]
Apologies, I realized I didn't implement things correctly hence the errors I was getting. I was able to run the function to perform the analysis and generate the plot. Thank you!

**Comment by OscarGVelasco** [comment]
@ttszen thanks for using the package! I am currently updating the documentation and function descriptions, albeit fixing some visualisation problems. So I encourage you to update the installation of LotOfCells frequently.

**Comment by ttszen** [comment]
@OscarGVelasco Yes absolutely! I will keep an eye out for further updates.
